---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: ""    
  resources:
    requests:
      storage: 2Gi
  selector: 
    matchLabels:
      app: mysql-pv    