---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  labels:
    app: wordpress-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany   
  resources:
    requests:
      storage: 2Gi